name       : midori
version    : '8.0'
release    : 16
source     :
    - https://github.com/midori-browser/core/releases/download/v8.0/midori-v8.0.tar.gz : 559ec7cc8903a423958f660f6ffb29f30e9e357b85c19ecd296e8911dc92be3c
license    : LGPL-2.1-or-later
component  : network.web.browser
summary    : Midori Web Browser - a lightweight, fast and free web browser using WebKit and GTK+
description: |
    Midori is a lightweight GTK+ web browser based on WebkitGtk. It features tabs, windows and session management, bookmarks stored with XBEL, searchbox based on OpenSearch, and user script support
libsplit   : no
builddeps  :
    - pkgconfig(gcr-3)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-bad-video-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libarchive)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - xorg-server-xvfb
    - vala
rundeps    :
    - gstreamer-1.0-libav
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    xvfb-run %ninja_check
