name        : midori
version     : 0.5.11
release     : 5
source     :
    - http://midori-browser.org/downloads/midori_0.5.11_all_.tar.bz2 : 96191a96be71144ae848a409fae5a1d6d52a00e583f33122081f47ead9c49c3d
license     : GPL-2.0+
summary     : Lightweight web browser GTK+ based
rundeps     :
    - glib-networking
builddeps   :
    - vala
    - pkgconfig(sqlite3)
    - pkgconfig(libsoup-gnome-2.4)
    - pkgconfig(gcr-3)
    - pkgconfig(granite)
    - pkgconfig(webkitgtk-3.0)
    - pkgconfig(librsvg-2.0)
description : |
    Midori is a lightweight GTK+ web browser based on WebkitGtk. It features tabs, windows and session management, bookmarks stored with XBEL, searchbox based on OpenSearch, and user script support
clang      : no
setup      : |
    ./configure --prefix=/usr \
                --disable-zeitgeist \
                --enable-gtk3 \
                --enable-granite
build      : |
    %make
install    : |
    %make_install
