name       : midori
version    : 0.5.11
release    : 11
source     :
    - http://midori-browser.org/downloads/midori_0.5.11_all_.tar.bz2 : 96191a96be71144ae848a409fae5a1d6d52a00e583f33122081f47ead9c49c3d
license    : GPL-2.0
component  : network.web.browser
summary    : Lightweight web browser GTK+ based
description: |
    Midori is a lightweight GTK+ web browser based on WebkitGtk. It features tabs, windows and session management, bookmarks stored with XBEL, searchbox based on OpenSearch, and user script support
builddeps  :
    - pkgconfig(gcr-3)
    - pkgconfig(granite)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsoup-gnome-2.4)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(zeitgeist-2.0)
    - vala
rundeps    :
    - glib-networking
setup      : |
    %patch -p0 < $pkgfiles/fix-build-with-valac-0.35.x.patch
    %patch -p1 < $pkgfiles/0001-Change-default-homepage-to-about-speed-as-DDG-can-be.patch
    %cmake -DHALF_BRO_INCOM_WEBKIT2=ON -DUSE_GRANITE=TRUE
build      : |
    %make
install    : |
    %make_install
