name       : midori
version    : '9.0'
release    : 17
source     :
    - https://github.com/midori-browser/core/releases/download/v9.0/midori-v9.0.tar.gz : 5e0a531455c47b0ff7589940aa2b0d9c16f59c99ba933e5fcdcab68114262016
license    : LGPL-2.1-or-later
component  : network.web.browser
summary    : Midori Web Browser - a lightweight, fast and free web browser using WebKit and GTK+
description: |
    Midori is a lightweight GTK+ web browser based on WebkitGtk. It features tabs, windows and session management, bookmarks stored with XBEL, searchbox based on OpenSearch, and user script support
libsplit   : no
builddeps  :
    - pkgconfig(gcr-3)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libarchive)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - xorg-server-xvfb
    - vala
rundeps    :
    - gstreamer-1.0-libav
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    xvfb-run %ninja_check
